### PR TITLE
FIX links to pcs formats

### PR DESCRIPTION
**Pull request by KEggensperger**
Fixes #231.

### CODE REVIEW

**Review by mfeurer — CHANGES_REQUESTED** [review]
Thanks a lot. Could you please also add these links into the docstring of the serialization classes so that they're easy to find there, too?

**Review by mfeurer — APPROVED** [review]

**Comment by mfeurer** [comment]
Hey @eddiebergman I just moved the documentation into module docstrings so that they are

1. available in the code and the rendered documentation
2. but only stored in one place (docstring)

What do you think?

**Review by eddiebergman — APPROVED** [review]
Seems good to me, as long as it renders correctly in the docs, I'm happy with it :)

**Comment by eddiebergman** [comment]
That's nice, big approve :)

**Pull request merged**
