### PR TITLE
Update wheel builder to include windows and osx

### PR DESCRIPTION
**Pull request by eddiebergman**
This PR builds wheels for the same distributions as supported in `sklearn` [github actions](https://github.com/scikit-learn/scikit-learn/blob/main/.github/workflows/wheels.yml).

This action also runs our suite of tests on these wheels which seems to complete without error.

The output of the test can be seen here: 
* https://github.com/eddiebergman/ConfigSpace/runs/4523610401?check_suite_focus=true

This also adds the `workflow_dispatch` event so that it can be triggered manually.

I would still advocate for some manual testing of the wheels produced in the artifacts on a seperate windows/mac device, seperate from the environment it was built on, if possile.

### CODE REVIEW

**Review by mfeurer — COMMENTED** [review]
That looks good. I'm wondering whether we now also need to run unit tests etc on Windows. We now know that we can build the wheels, but we don't know whether our packages work there.

**Comment by eddiebergman** [comment]
Click in to the tests, it looks like it runs the unittests on those wheels.

**Comment by mfeurer** [comment]
Thanks a lot for the pointer. This is excellent. I'm wondering whether we should test these other platforms during the regular unit tests as well? But that would be a separate PR I assume?

**Comment by eddiebergman** [comment]
Let's do it as a separate PR, if we run into build issues when doing unit-tests then we might want to have dedicated changes there.

**Pull request merged**
