### PR TITLE
Cleanup setup.py. If numpy is not installed, attempt to install it with pip.

### PR DESCRIPTION
**Pull request by aravind-vasudevan**
Adding numpy to install_requires and setup_requires alone doesn't suffice as setup.py itself uses numpy (to get the headers using np.get_include()). So attempt to install it using pip if there is an error in importing numpy. Conservatively install numpy specific to the user (using --user) to avoid overwriting global/needing permissions to install for all users.

### CODE REVIEW

**Comment by mfeurer** [comment]
Hi @aravind-vasudevan thanks for having a look at this.

Three minor things which are only partially related to the way you set up installation of numpy:

* could you please remove the installation of numpy from the file `ci_scripts/install.sh` to test that your solution is working?
* make sure that flake8 emits no warnings? You can run it locally with `bash ci_scripts/flake8_diff.sh`.
* the installation issue also applies to cython. Could you please check if there's a similar fix?

Regarding your implementation, I don't think that installing a package into the user dir with pip is the right way to go as this assumes that pip is installed and that the user is not using anaconda. I would prefer a solution which is closer to the way setuptools handles it itself like in Auto-sklearn: https://github.com/automl/auto-sklearn/blob/master/setup.py . As you can see, there's no import of cython & numpy and no use of pip.

**Comment by aravind-vasudevan** [comment]
Hi @mfeurer. I have fixed all the above issues (haven't looked into Cython yet). I have moved over to handling the dependency the way auto-sklearn does it, but it doesn't seem to work. I tried running the setup.py from auto-sklearn and that appears to work. But my current edit to ConfigSpace/setup.py fails with the following: 
```
/usr/bin/python3.7 setup.py install --user    
running install
running bdist_egg
running egg_info
writing ConfigSpace.egg-info/PKG-INFO
writing dependency_links to ConfigSpace.egg-info/dependency_links.txt
writing requirements to ConfigSpace.egg-info/requires.txt
writing top-level names to ConfigSpace.egg-info/top_level.txt
Traceback (most recent call last):
  File "setup.py", line 107, in <module>
    classifiers=CLASSIFIERS
  File "/usr/lib/python3/dist-packages/setuptools/__init__.py", line 129, in setup
    return distutils.core.setup(**attrs)
  File "/usr/lib/python3.7/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/usr/lib/python3.7/distutils/dist.py", line 966, in run_commands
    self.run_command(cmd)
  File "/usr/lib/python3.7/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/usr/lib/python3/dist-packages/setuptools/command/install.py", line 67, in run
    self.do_egg_install()
  File "/usr/lib/python3/dist-packages/setuptools/command/install.py", line 109, in do_egg_install
    self.run_command('bdist_egg')
  File "/usr/lib/python3.7/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/usr/lib/python3.7/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/usr/lib/python3/dist-packages/setuptools/command/bdist_egg.py", line 163, in run
    self.run_command("egg_info")
  File "/usr/lib/python3.7/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/usr/lib/python3.7/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/usr/lib/python3/dist-packages/setuptools/command/egg_info.py", line 278, in run
    self.find_sources()
  File "/usr/lib/python3/dist-packages/setuptools/command/egg_info.py", line 293, in find_sources
    mm.run()
  File "/usr/lib/python3/dist-packages/setuptools/command/egg_info.py", line 524, in run
    self.add_defaults()
  File "/usr/lib/python3/dist-packages/setuptools/command/egg_info.py", line 560, in add_defaults
    sdist.add_defaults(self)
  File "/usr/lib/python3.7/distutils/command/sdist.py", line 228, in add_defaults
    self._add_defaults_ext()
  File "/usr/lib/python3.7/distutils/command/sdist.py", line 311, in _add_defaults_ext
    build_ext = self.get_finalized_command('build_ext')
  File "/usr/lib/python3.7/distutils/cmd.py", line 299, in get_finalized_command
    cmd_obj.ensure_finalized()
  File "/usr/lib/python3.7/distutils/cmd.py", line 107, in ensure_finalized
    self.finalize_options()
  File "setup.py", line 29, in finalize_options
    import numpy
ModuleNotFoundError: No module named 'numpy'
Error in sys.excepthook:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/apport_python_hook.py", line 63, in apport_excepthook
    from apport.fileutils import likely_packaged, get_recent_crashes
  File "/usr/lib/python3/dist-packages/apport/__init__.py", line 5, in <module>
    from apport.report import Report
  File "/usr/lib/python3/dist-packages/apport/report.py", line 30, in <module>
    import apport.fileutils
  File "/usr/lib/python3/dist-packages/apport/fileutils.py", line 23, in <module>
    from apport.packaging_impl import impl as packaging
  File "/usr/lib/python3/dist-packages/apport/packaging_impl.py", line 24, in <module>
    import apt
  File "/usr/lib/python3/dist-packages/apt/__init__.py", line 23, in <module>
    import apt_pkg
ModuleNotFoundError: No module named 'apt_pkg'

Original exception was:
Traceback (most recent call last):
  File "setup.py", line 107, in <module>
    classifiers=CLASSIFIERS
  File "/usr/lib/python3/dist-packages/setuptools/__init__.py", line 129, in setup
    return distutils.core.setup(**attrs)
  File "/usr/lib/python3.7/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/usr/lib/python3.7/distutils/dist.py", line 966, in run_commands
    self.run_command(cmd)
  File "/usr/lib/python3.7/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/usr/lib/python3/dist-packages/setuptools/command/install.py", line 67, in run
    self.do_egg_install()
  File "/usr/lib/python3/dist-packages/setuptools/command/install.py", line 109, in do_egg_install
    self.run_command('bdist_egg')
  File "/usr/lib/python3.7/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/usr/lib/python3.7/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/usr/lib/python3/dist-packages/setuptools/command/bdist_egg.py", line 163, in run
    self.run_command("egg_info")
  File "/usr/lib/python3.7/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/usr/lib/python3.7/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/usr/lib/python3/dist-packages/setuptools/command/egg_info.py", line 278, in run
    self.find_sources()
  File "/usr/lib/python3/dist-packages/setuptools/command/egg_info.py", line 293, in find_sources
    mm.run()
  File "/usr/lib/python3/dist-packages/setuptools/command/egg_info.py", line 524, in run
    self.add_defaults()
  File "/usr/lib/python3/dist-packages/setuptools/command/egg_info.py", line 560, in add_defaults
    sdist.add_defaults(self)
  File "/usr/lib/python3.7/distutils/command/sdist.py", line 228, in add_defaults
    self._add_defaults_ext()
  File "/usr/lib/python3.7/distutils/command/sdist.py", line 311, in _add_defaults_ext
    build_ext = self.get_finalized_command('build_ext')
  File "/usr/lib/python3.7/distutils/cmd.py", line 299, in get_finalized_command
    cmd_obj.ensure_finalized()
  File "/usr/lib/python3.7/distutils/cmd.py", line 107, in ensure_finalized
    self.finalize_options()
  File "setup.py", line 29, in finalize_options
    import numpy
ModuleNotFoundError: No module named 'numpy'

```

**Comment by mfeurer** [comment]
I just added `'numpy'` to `SETUP_REQS` and that seems to do the trick.

**Comment by aravind-vasudevan** [comment]
@mfeurer Wow, I cannot believe I missed that! Serves me right for going back and forth between fix attempts

**Comment by mfeurer** [comment]
I didn't see it immediately as well, I had to use [meld](http://meldmerge.org/) and go line by line.

**Comment by aravind-vasudevan** [comment]
@mfeurer Apologies, this kinda fell off my radar. Is there anything else you are waiting on to accept this PR?

**Comment by aravind-vasudevan** [comment]
@mfeurer bump. Is there anything else you are waiting on to close this issue and accept this PR?

**Comment by mfeurer** [comment]
Sorry, I currently don't have the time to look into this repository. I'll try to get back to the ConfigSpace next week.

**Comment by mfeurer** [comment]
Thanks a lot, I just merged this.

**Comment by aravind-vasudevan** [comment]
@mfeurer thanks! does this need to be ported to the other repos as well?

**Comment by mfeurer** [comment]
We didn't implement this for SMAC3 yet.

**Pull request merged**
