### PR TITLE
add copy of meta field in hyperparameters (#176)

### PR DESCRIPTION
**Pull request by mickare**
Fix for  #176

### CODE REVIEW

**Comment by mfeurer** [comment]
Good catch and thanks a lot for the PR. There's currently a comma missing around line 1400 in hyperparemeters.pyx, it would be great if you could fix that.

Could you please let us know how you found that issue and whether you think there could be unit tests for copy detecting such issues in the future?

**Comment by mickare** [comment]
> Good catch and thanks a lot for the PR. There's currently a comma missing around line 1400 in hyperparemeters.pyx, it would be great if you could fix that.
> 
> Could you please let us know how you found that issue and whether you think there could be unit tests for copy detecting such issues in the future?

We use the meta field for reconstructing a nested configuration dict and it failed.
This issue could be found by testing randomized mock hyperparameters.

In our case, the configuration space has branching sub-spaces that can contain similar naming schemes, which would cause collisions in the flat ConfigSpace data structure. Therefore a "virtual/fake" path in the nested configuration is used for the hyperparameters' names. The real dict path is stored in the meta field.

**Example:**
Custom nested configspace (lists are choices, where first parameter is the key)
```json
{
  "branches": [
    { "type": "A", "some_parameter":  "1:10", "nested": {...} },
    { "type": "B", "other_parameter": "0.1:0.9"}
  ]
}
```
Parsed to configspace
```json
{
  "hyperparameters": [
    {
      "name": "branches/type",
      "type": "categorical",
      "choices": [ "A", "B" ],
      "default":  "A",
      "probabilities": null
    },
    {
      "name": "branches/type=A/some_parameter",
      "type": "uniform_int",
      "log": false,
      "lower": 1,
      "upper": 10,
      "default": 5
    },
    {
      "name":  "branches/type=A/nested/...",
      ...
    },
    ...
    {
      "name":  "branches/type=B/other_parameter",
      "type": "uniform_float",
      "log": false,
      "lower": 0.1,
      "upper": 0.9,
      "default": 0.5
    },
  ],
  "conditions": [
    {
      "child": "branches/type=A/some_parameter",
      "parent": "branches/type",
      "type": "EQ",
      "value": "A",
    },
    {
      "child":  "branches/type=A/nested/...",
      "parent": "branches/type",
      "type": "EQ",
      "value": "A",
    },
    ...
    {
      "child": "branches/type=B/other_parameter",
      "parent": "branches/type",
      "type": "EQ",
      "value": "B",
    },
  ],
  "forbiddens": [],
  "python_module_version": "0.4.17",
  "json_format_version": 0.2
```

Reconstructed nested configuration from the meta field
```json
{
  "branches":  { 
    "type": "A", 
    "some_parameter":  3,
    "nested": { ... }
  },
}
```
```json
{
  "branches": { 
    "type": "B", 
    "other_parameter":  0.7
  }
}
```

**Comment by mfeurer** [comment]
>  This issue could be found by testing randomized mock hyperparameters.

Would you be willing to add this? Otherwise, I would just merge.

**Comment by mickare** [comment]
> Would you be willing to add this? Otherwise, I would just merge.

This is not a mock test, but I added a simple integration test for the configuration space ( 5f3c72c ).

**Review by mfeurer — APPROVED** [review]

**Pull request merged**
